### ISSUE TITLE
How proxy from subdomain?

### ISSUE THREAD

**Issue by alukos** [nuxt-community/axios-module#121]
package.json:
```js
{
  "name": "my-app",
  "scripts": {
    "dev": "nuxt"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.1.1",
    "nuxt": "^1.4.0"
  }
}
```
nuxt.config.js:
```js
module.exports = {
  modules: [
    '@nuxtjs/axios'
  ],
  axios: {
    proxy: true
  },
  proxy: {
    // Its work but need proxy from subdomain
    // '/api/': {
    //   target: 'http://localhost:8080',
    //   pathRewrite: {
    //     '^/api/': ''
    //   }
    // }

    // Its not work:
    '/': {
       target: 'http://localhost:3000',
       router: {
         'api.localhost:3000': 'localhost:8080'
       }
    }
    //   curl http://localhost:8080
    //   Hello from API
    //   curl http://localhost:3000
    //   [HPM] Error occurred while trying to proxy request / from localhost:3000 to http://localhost:3000 (ENOTFOUND) (https://nodejs.org/api/errors.html#errors_common_system_errors)
  }
}
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/axios-module/issues/c101">#c101</a>)</em></sub></div>

**Comment by msprogramando** [comment]
Hi alukos,

I alomst got it working with "@nuxtjs/proxy" on top of "@nuxtjs/axios". 
https://github.com/nuxt-community/proxy-module

With that package you can add a proxy url like the example below. Then all ajax requests to /api will be forwared to http://api.domain.tld/api

  axios: {
    proxy: true,
    logLevel: 'debug',
  },
  proxy: {
     '/api': 'http://api.domain.tld'
  },

On big advantage of this way is you don't need the npm cors package on api side. Because of not figuring out how to implement his, at the end I am using the baseURL togehter with cors package.

Perhaps you came to this package as well? Or how did you solve it?

**Comment by danchristian** [comment]
How has this issue still open 😩

**Comment by ricardogobbosouza** [comment]
See https://axios.nuxtjs.org/options#proxy

@pi0 can closed?
