### ISSUE TITLE
API_URL env var only works when set via npm not when you set it in the nuxt.config

### ISSUE THREAD

**Issue by vordimous** [nuxt-community/axios-module#138]
### Version

[5.3.1](https://github.com/nuxt-community/axios-module/releases/tag/5.3.1)

### Reproduction link

[https://github.com/nuxt-community/axios-module](https://github.com/nuxt-community/axios-module)

### Steps to reproduce

- create a project
- add a different URL via env vars in the nuxt.config.js

### What is expected ?

the baseURL option changes

### What is actually happening?

the baseURL option remains defaulted

### Additional comments?

expected behavior works when the env var is set via npm at run time i.e. "API_URL=htt://someOtherUrl npm run dev"

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/axios-module/issues/c123">#c123</a>)</em></sub></div>

**Comment by renoirb** [comment]
I had a similar issue while running within Koa like clarkdo/hare does.
([see also my notes in the context of my current PR to the project](https://github.com/clarkdo/hare/pull/339#issuecomment-398563718))

Something could be done by creating a client-side only plugin and superseed `$nuxt.$axios.defaults.baseURL`.

To attempt working on the problem, I've created a repository and am attempting to be able to build Nuxt, then, run the built version and set `HOST` and `PORT` environment variables and Axios module would know what to do.  It looks related to the issue here, that's why I'm pasting my workspace here, it might be a good **Reproduction link**

In case that's of interest to somebody, here is the [experiment/reproduction repository](https://github.com/renoirb/experiments-nuxt-koa-env-runtime-201806)

In the [branch **rework-hare-20180619**](https://github.com/renoirb/experiments-nuxt-koa-env-runtime-201806/tree/rework-hare-20180619), I could make it work.

**Comment by ricardogobbosouza** [comment]
@manniL I think this can be closed

**Comment by vordimous** [comment]
Thanks for the hard work!
