### ISSUE TITLE
axios withCredentials not being passed from nuxt.config.js

### ISSUE THREAD

**Issue by daniel-payne** [nuxt-community/axios-module#168]
i had a problem that withCredentials was not being picked up from the nuxt.config.js
```
  axios: {
    withCredentials: true,
    baseURL: process.env.DATA_API 
  },
```

so i added an axios plugin with
```
export default function({ $axios, redirect }) {
  $axios.onRequest(config => {
    config.withCredentials = true

    return config
  })
}
```

and everything worked for me, 
any idea what i was doing wrong?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c175">#c175</a>)</em></sub></div>

**Comment by husayt** [comment]
İ had the same problem and resolved similarly. But that is a serious issue and needs to be reopened

**Comment by husayt** [comment]
This is still an  issue. Here is a quick workaround, you can do in `nuxt.config`:

```
axios: {
    credentials: true,
    init(axios) {
      axios.defaults.withCredentials = true
    }
  } 
```

**Comment by tockn** [comment]
@daniel-payne @husayt 
This is in the specification, not a bug.  
According to documentation and source code, `credentials` option only work when axios request to  `baseURL` or relative path.  
see: 
https://axios.nuxtjs.org/options#credentials
https://github.com/nuxt-community/axios-module/blob/dev/lib/plugin.js#L80

**Comment by daukadolt** [comment]
@tockn 

I'm having the same issue. Without 
`axios: {
withCredentials: true
}`
no requests to baseUrl + /path/to/endpoint have credentials. Adding the above-mentioned code piece to `nuxt.config.js` helps, however another issue takes place, which I've described here https://cmty.app/nuxt/axios-module/issues/c221#comment-5c855a0c4f9b2d0bea516c6f.

Interestingly:

1. With `axios: {withCredentials: true}` SSR requests don't have the credentials, but all the requests that take place when moving from one page to another - i.e. on the client - do have the credentials.
2. Without `axios: {withCredentials: true}` no requests have credentials set.

**Comment by Faisal0sal** [comment]
I"m having the same issue with SSR, any luck?

**Comment by tuz1k** [comment]
@daukadolt any solutions?

**Comment by mcordoba** [comment]
Same problem here...

I tried with this code on nuxtServerConfig:

```javascript
if (req.headers.cookie) {
        axios.defaults.headers['Cookie'] = req.headers.cookie
      }
```

But as the axios object is shared across requests, it causes problems with mixing sessions...

**Comment by lukaVarga** [comment]
It's worth pointing out that for `post` requests with a payload, the solutions mentioned here are not enough (at least they weren't in my case). There's an open issue in the Axios repo (see [here](https://github.com/axios/axios/issues/876)) - basically, you have to manually add the `withCredentials: true` when calling `axios.post`

I handle all my API communication via a custom `ApiService` (instead of directly via axios) and the exposed methods are really simple. So, for `post` requests, just making sure that the `withCredentials: true` is present in the last argument is what does the trick:
```
  public async post<T>(url: string, body: any, config?: AxiosRequestConfig): Promise<AxiosResponse<T>> {
    return axios.post(`${this.baseUrl}/${url}`, body, { ...{ withCredentials: true }, ...config });
  }
```

**Comment by ricardogobbosouza** [comment]
@pi0 can closed?
See https://github.com/nuxt-community/axios-module/issues/168#issuecomment-471670927

**Comment by denysaw** [comment]
@pi0, @tockn

If you are talking about this comparison (selected on a snap), then you clearly see, that it takes place ONLY when `withCredentials` isn't set. And we ARE setting that. I also doing only API_URL (baseUrl) and relative requests and no Cookies in my requests :(
When manually adding `withCredentials: true` option to a single request, everything is ok. So that's definitely a bug.

![image](https://user-images.githubusercontent.com/5720101/88102896-91d3bc80-cba0-11ea-89b8-c7692be573f2.png)

**Comment by syntheticgoo** [comment]
> i had a problem that withCredentials was not being picked up from the nuxt.config.js
> 
> ```
>   axios: {
>     withCredentials: true,
>     baseURL: process.env.DATA_API 
>   },
> ```
> 
> so i added an axios plugin with
> 
> ```
> export default function({ $axios, redirect }) {
>   $axios.onRequest(config => {
>     config.withCredentials = true
> 
>     return config
>   })
> }
> ```
> 
> and everything worked for me,
> any idea what i was doing wrong?
> 
> _This question is available on [Nuxt](https://cmty.app/nuxt) community ([#c175](https://cmty.app/nuxt/axios-module/issues/c175))_

I has to add this plugin to nuxt.config.js auth options as well, to allow cookies to be set from login endpoint.
```  /*
  ** Auth strategies
  */
  auth: {
    plugins: ['@plugins/axios.js'], // This ensures that we can set cookies from API
  }
...```

**Comment by 13protons** [comment]
Maybe someone finds this helpful - as a nuxt noob I never changed my async fetch calls to use `this.$axios.$get` (or $post, whatever). As soon as I did that in my vue components all worked as advertised.
