### ISSUE TITLE
High vulnerability - Denial of Service

### ISSUE THREAD

**Issue by artmarydotir** [nuxt-community/axios-module#366]
npm audit security report for axios module

**version: 5.10.3**
**path: @nuxtjs/axios > @nuxtjs/proxy > http-proxy-middleware > http-proxy**
******
![Screenshot from 2020-05-17 07-15-26](https://user-images.githubusercontent.com/11363931/82134539-3686f600-980e-11ea-9965-16af6155522e.png)

**Comment by pi0** [comment]
Hi @artmarydotir thanks for reporting :green_heart: I'm going to update both proxy and axios modules however according to the [advisory#1486](https://www.npmjs.com/advisories/1486), it is not effective on the way we use middleware:

> This is only possible when the proxy server sets headers in the proxy request using the proxyReq.setHeader function.

**Comment by kreig303** [comment]
understood if this does not directly impact the software. however some of us are using vulnerability scanning software in company repos and this still gets flagged as a `HIGH`... which is a problem for us because... build systems.

any chance you could accelerate a release for this dep? 

willing to PR the dep bump into the repo if desired @pi0 thx! :)

**Comment by pi0** [comment]
[v5.11.0](https://github.com/nuxt-community/axios-module/releases/tag/v5.11.0) releaed.

**Comment by kreig303** [comment]
¡gracias señor!
