### ISSUE TITLE
axios dosn't send cookies for each request

### ISSUE THREAD

**Issue by redbayoub** [nuxt-community/axios-module#474]
Hi,
I'm using Laravel sanctum and nuxt/auth
and after setting 
```
axios: {
    credentials: true,
    withCredentials: true,
  },
```
in my nuxt.config.js  axios dosn't send cookies which are set by laravel

My workaround:
1- I added axios.js to plugin directory 
```
import axios from 'axios'

axios.defaults.withCredentials = true
```
2- I added the plugin to plugins array
`  plugins: [ '~/plugins/axios'],`

my package.json 
```
"dependencies": {
    "@nuxtjs/auth-next": "5.0.0-1611574754.9020f2a",
    "@nuxtjs/axios": "^5.12.5",
   ...
}
```

**Comment by pi0** [comment]
Hi @redbayoub. To extend axios instance, you need to extend `$axios` ([docs](https://axios.nuxtjs.org/extend)). Also credentials option enables it only for baseURL. (also note that for auth module, you need to use `auth.plugins` option ([docs](https://auth.nuxtjs.org/recipes/extend)). 

Anyway an issue with reprodution in auth module repository would be great since seems issue backs to auth.

**Comment by redbayoub** [comment]
thanks @pi0  I didn't know that credentials option is only for baseURL and now I see the reason behind that
