### ISSUE TITLE
this.$axios request always return OPTIONS instead GET, POST, PUT, DELETE

### ISSUE THREAD

**Issue by ngodink** [nuxt-community/axios-module#71]
**components/index.vue**
```
<template>
  <div>
    <p>{{ $store.state.token }}</p>
    <v-btn class @click="reqs">click to request</v-btn>
  </div>
</template>

<script>
export default {
  methods: {
    async reqs (ctx) {
      let me = await this.$axios.get('/cek')
      console.log(me.data)
    }
  }
}
</script>
```
so, i click "Click to request" and get this response from server
![x](https://user-images.githubusercontent.com/32119513/34551756-3473aaba-f14f-11e7-9aa0-a9c3f6b1afed.PNG)
I have tried with postman, and the result is normally, but, why if i use nuxt axios modules the request always changed to OPTIONS (instead GET, POST, PUT)... what should i do ?

NOTE: 
I use setToken in requestInterceptors placed **nuxt.config.js**

**Comment by pi0** [comment]
Hey. Would you please share nuxt.config.js?

**Comment by ngodink** [comment]
this is my **nuxt.config.js**
```
var path = require('path')
var environment = {
  APP_NAME: 'Ngodink administration',
  THIS_URL: 'http://127.0.0.1:3001',
  AUTH_URL: 'http://127.0.0.1:3000',
  API_URL: 'http://127.0.0.1/ngodink/api/public'
}

module.exports = {
  /*
  ** Modules
  */
  srcDir: __dirname, 
  buildDir: '.nuxt/admin',
  env: environment,
  plugins: [
    {src: '~/plugins/vue-notifications', ssr: false}
  ],
  modules: [
    '@nuxtjs/axios'
  ],
  axios: {
    baseURL: environment.API_URL,
    requestInterceptor: (config, {store}) => {
      config.headers.common['Authorization'] = 'Bearer ' + store.state.token
      return config
    }
  },
  build: {
    vendor: [
      '~/plugins/vue-notifications',
      'lodash'
    ],
    extend (config, ctx) {
      config.resolve.alias['~shared'] = path.join(__dirname, '../shared')
      if (ctx.dev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  }
}

```

**Comment by pi0** [comment]
This seems because of not CORS supporting your API server. (Between port 80 and 3000)
Please try [this](https://chrome.google.com/webstore/detail/cors-toggle/jioikioepegflmdnbocfhgmpmopmjkim?hl=en) or [this](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en) chrome extensions to temporary disable CORS.

For long term, you have to provide `Allow-Control-Allow-Origin: *` header from API responses which is not secure or use nuxt [proxy module](https://github.com/nuxt-community/modules/tree/master/packages/proxy) which is provided for an exact same reason.

**Comment by ngodink** [comment]
@pi0 , i have set my API server configuration to `Allow-Control-Allow-Origin:  *`.. I have tried with php composer and server with different port, and try again with axios, the request is always changed to OPTIONS again.
But, i try to access (get, post, delete, put) my API resource with POSTMAN, and the give a success response. so, is there something wrong with my nuxt-axios module ?

**Comment by ngodink** [comment]
wait, if i use this, it works
```
async asyncData ({app}) {
  let me = await app.$axios.get('/cek')
  console.log(me.data)
}
```
but, not work with `this.$axios` (work with asyncData `app.$axios`)

**Comment by pi0** [comment]
Your second request inside `asyncData` is working because it is being done in server side (via SSR)

request is not being changed to OPTIONS, that's just XHR which is checking CORS with OPTIONS :)

What if you add `Access-Control-Allow-Credentials: true` header too in API?

As another option, setting `credentials` option to `false` may resolve this issue but this makes requests without sending cookies.

```js
axios: {
  credentials: false
}
```

**Comment by ngodink** [comment]
@pi0 , i have tried too, but it still has not solve the problem..

**Comment by ngodink** [comment]
thanks @pi0 the problem is solved :+1:

**Comment by kristinadinellari** [comment]
@ngodink how did you solve it ?

**Comment by H4midR** [comment]
> @ngodink how did you solve it ?

if you remove Custom Headers , it's fine. but custom headers is needed too ,
I have the same problem and looking for solving it, I also tried transformRequest and add header there , but still change the request method to OPTIONS.
any idea?
