### ISSUE TITLE
Can setupHelpers be before initHook?

### ISSUE THREAD

**Issue by yariksav** [nuxt-community/axios-module#76]
https://github.com/nuxt-community/axios-module/blob/f71fa8d2c43a986a83c7077a2e67dd7f7bf3c9e4/lib/plugin.template.js#L183-L193
can call of setupHelpers(axios) be before initHook(axios, ctx)? 
for example 
```

  // Setup axios helpers
  setupHelpers(axios)

  <% if (options.init) { %>
  await initHook(axios, ctx)
  <% } %>

```
This because if I call store.dispatch('someRegularAction') in axios.init function, methods $post, $get, ... are not available...

**Comment by pi0** [comment]
Hi. With release `5.0.0` this is possible using a plugin instead of `initHook`. 

Please see [Extending Axios](https://github.com/nuxt-community/axios-module#extending-axios) section. Also please make sure to read [Migration Guide](https://github.com/nuxt-community/axios-module/wiki/Migration-Guide).

If any problem exists, feel free opening a **new Issue or PR**.

**Comment by yariksav** [comment]
Thanks
